version: "3.9"

services:
  database:
    container_name: dbt-postgres
    image: postgres:14
    restart: always
    environment:
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: postgres
    ports:
      - 5432:5432
  dbt:
    build: .
    image: dbt-server
    container_name: dbt-app
    ports:
      - 8000:80
    links:
      - database:db
